CS3219-AY2324S1/ay2324s1-course-assessment-g23

- frontend/src/services/questionBank.ts
Added the following function/interface signatures:
```ts
/** Represents a question in the question bank. */
export interface Question {
id: number
title: string
description: string
category: string[]
complexity: 'Easy' | 'Medium' | 'Hard'
}
/**
* Stores a new question into the localStorage.
*
* @param {Omit<Question, 'id'>} question The question object without the ID.
* @returns {Promise<void>} Resolves when the question is stored successfully.
*/
export const storeQuestion = async (question: Omit<Question, 'id'>): Promise<void>
/**
* Retrieves all questions from the localStorage.
*
* @returns {Promise<Question[]>} An array of questions.
*/
export const getQuestions = async (): Promise<Question[]>
/**
* Updates an existing question in the localStorage.
*
* @param {Pick<Question, 'id'> & …
```
> Create CRUD functions for question bank

- api/app/database.py
- api/app/main.py
- api/app/requestModels.py
Added implementation for API to update user information.
Some minor modifications to GET and POST functions:
1. Changed response of GET to `False` instead of `null` if `user_id` doesn't exist (for potential future handling of such cases)
2. Fixed POST returning a `user_id` even though user creation was unsuccessful
> Add Update User Info API

- api/app/database.py
- api/app/main.py
- api/app/requestModels.py
- api/app/tests/create_user_test.py
- api/app/tests/get_user_test.py
- api/app/tests/update_user_info_tests.py
> Add basic test Files for users API

- frontend/src/components/QuestionTable.tsx
- frontend/src/components/ReadOnlyRow.tsx
Previously, edited description was not saved to local storage.
> Fix edit desctiption bug

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/QuestionTable.tsx
- frontend/src/stores/questionStore.ts
Refer to `/frontend/src/stores/questionStore.ts` for documentation on how to use the new global states
> Replace `questions` React state with global state using `react-query`

- frontend/src/services/questionBank.ts
- frontend/src/services/users.ts
- frontend/src/stores/userStore.ts
Global React states and their usage documentation found in `/frontend/src/stores/userStore.ts`
> Add frontend API functions & global states for users

- api/app/database_functions/question_functions.py
- api/app/database_functions/user_functions.py
> Change update API calls to require all fields

- frontend/src/api/error.ts
- frontend/src/api/questions.ts
- frontend/src/api/users.ts
- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/components/UserTable/UserTable.tsx
- frontend/src/stores/questionStore.ts
- frontend/src/stores/userStore.ts
Very basic error message display; it's:
- not yet in darkmode (need to tinker with MUI themes) 
- stretches beyond the other components. 
I'll let @afiqzu handle the nice-ifying of the UI.
The displayed error messages are copied straight from the API response's "detail" JSON value. If yall wanna change the message, do it in the backend.
> Add error handling on frontend

- api/app/database_functions/question_functions.py
- api/app/database_functions/session_functions.py
- api/app/database_functions/user_functions.py
- api/app/database_functions/utils/sessions_util.py
- api/app/database_functions/utils/users_util.py
- api/app/main.py
- api/app/requestModels.py
- api/app/tests/user_functions_tests/update_user_info_tests.py
- database/init.sql
- frontend/src/services/users.ts
- Add role column to users
- Create admin role on initialization
- Use session id to validate user permissions for changes in application
> Assignment 3 features

- frontend/src/components/AlertMessage.tsx
- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/components/UserTable/UserTable.tsx
- frontend/src/styles/AlertMessage.css
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/93078202/6bb56471-472e-4364-98f7-8c15b0180def
> Add UI for error message popup

- frontend/src/pages/Login.tsx
- frontend/src/pages/Signup.tsx
> Change logo path reference to exclude '/public/'

- api/app/database_functions/user_functions.py
- api/app/main.py
- Allow account owners to view their own account details
> Update permissions for get_user API

- api/app/database_functions/user_functions.py
- api/app/main.py
Reverts CS3219-AY2324S1/ay2324s1-course-assessment-g23#71
Reverting and putting the fix in `assignment-4` branch instead. This is to prevent merge conflicts later when `assignment-3` merges into `assignment-4`.
> Revert "Update permissions for get_user API"

- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/auth.ts
- frontend/src/api/questions.ts
- frontend/src/api/users.ts
- frontend/src/components/EditProfile.tsx
- frontend/src/components/Navbar.tsx
- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/components/UserTable/UserTable.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Questions.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/pages/Users.tsx
- frontend/src/stores/sessionStore.ts
- frontend/src/stores/userStore.ts
Requires the following bugs to be fixed before it can work properly:  
#60, #62, #73, #74, #81
> Implement frontend logic for Assignment 3

- api/app/database_functions/session_functions.py
- api/app/database_functions/user_functions.py
- api/app/database_functions/utils/sessions_util.py
- api/app/database_functions/utils/users_util.py
- api/app/main.py
- api/app/requestModels.py
Just some temporary fixes for most of the backend bugs
> Temp fix backend

- start_containers.sh
Just some minor commit use to test some new Github PR settings
> Test PR for testing new PR settings

- frontend/src/components/QuestionTable/QuestionEditableRow.tsx
- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
- frontend/src/components/UserTable/UserEditableRow.tsx
- frontend/src/components/UserTable/UserReadOnlyRow.tsx
- frontend/src/components/UserTable/UserTable.tsx
- frontend/src/index.css
- frontend/src/styles/QuestionTable.css
- frontend/src/styles/UserTable.css
> Edit UI for QuestionTable and UserTable

- frontend/src/components/Navbar.tsx
@afiqzu im removing the 2 `console.log` from ur `Navbar.tsx` component
> Remove artifact `console.log` from frontend code

- frontend/src/stores/userStore.ts
> Avoid setting user-store data as 'undefined'

- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
> Fix question description textbox not clearing on cancel

- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
> Implement frontend error handling for failed question description edit

- api/app/database_functions/session_functions.py
- api/app/database_functions/user_functions.py
- api/app/database_functions/utils/sessions_util.py
- api/app/database_functions/utils/users_util.py
- api/app/main.py
- api/app/requestModels.py
Reverts CS3219-AY2324S1/ay2324s1-course-assessment-g23#87
Reverts temp fixes in preparation to merge into `assignment-4` branch (which should have the official backend bug-fixes)
> Revert "Temp fix backend"

- api/app/database_functions/session_functions.py
- api/app/database_functions/utils/sessions_util.py
Reverts CS3219-AY2324S1/ay2324s1-course-assessment-g23#66
Revert this fix as it's conflicting with the `assignment-4` code. Bug #59 should already be fixed on `assignment-4` by the commit a5e5040a8ec1c8d75043cffa8da52a411a251e1b.
> Revert "Fix for #59"

- backend_services/api_gateway/main.py
- backend_services/users_service/api/app/controllers/sessions_controller.py
- backend_services/users_service/api/app/main.py
- backend_services/users_service/api/app/utils/sessions_util.py
- backend_services/users_service/test/user_login_test.py
- docker-compose.yaml
- frontend/src/api/questions.ts
- frontend/src/api/users.ts
Fix CORS error
Integrate session id's into cookies
> Reconcile docker changes pt2

- docker-compose.yaml
Fix the problem where docker is creating random anonymous volumes everytime it starts, like:
> Fix anonymous volumes being created

- backend_services/api_gateway/main.py
> Fix api-gateway not throwing correct HTTP status

- backend_services/api_gateway/utils/api_gateway_util.py
> Fix code typo in `_map_role_permission` func.

- frontend/src/styles/EditProfile.css
> Fix icon bug

- backend_services/users_service/api/app/controllers/sessions_controller.py
- backend_services/users_service/api/app/utils/sessions_util.py
- backend_services/users_service/database/init.sql
> Fix session creation/expiration-times bugs

- backend_services/questions_service/database/init.sql
Fixes #95
Also changed title to TEXT incase the title is longer than 255 char
> Change questions' title & description from `VARCHAR` -> `TEXT`

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/MatchBar.tsx
- frontend/src/components/MatchingScreen.tsx
- frontend/src/index.css
- frontend/src/pages/Questions.tsx
Add matching screen animation using Framer Motion
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/93078202/540c2423-0732-4f46-8973-b2fcc9d0a8ba
> Assignment 5

- backend_services/api_models/api_models/users.py
- backend_services/users_service/api/app/controllers/users_controller.py
- frontend/src/api/users.ts
- frontend/src/components/UserTable/UserEditableRow.tsx
- frontend/src/components/UserTable/UserReadOnlyRow.tsx
- frontend/src/components/UserTable/UserTable.tsx
> Remove user hashed-password from GET users API & from frontend

- backend_services/users_service/database/init.sql
> Cascade delete sessions when user is deleted

- frontend/src/api/users.ts
- frontend/src/components/EditProfile.tsx
- frontend/src/components/UserTable/UserEditableRow.tsx
- frontend/src/components/UserTable/UserTable.tsx
> Match frontend's UPDATE user API call with backend's UPDATE user/user-role API

- backend_services/api_gateway/app/main.py
- backend_services/api_gateway/app/utils/api_gateway_util.py
- backend_services/users_service/api/app/controllers/users_controller.py
- backend_services/users_service/api/app/utils/users_util.py
> Fixes for assignment 4

- backend_services/api_gateway/app/utils/api_gateway_util.py
to avoid having merge conflicts with Jerome's upcoming matching service.
@swxk19 my bad. i forgot @Yaladah will be making major changes to this part, so we shouldn't touch it
> Revert type-hintings for 'connect_matching_service_websocket' function

- backend_services/api_gateway/app/main.py
- backend_services/api_gateway/app/utils/api_gateway_util.py
- backend_services/matching_service/Dockerfile
- backend_services/matching_service/app/main.py
- backend_services/matching_service/app/matching.py
- backend_services/matching_service/app/matching_util.py
- backend_services/matching_service/app/queue_manager.py
- backend_services/matching_service/rmq_server/Dockerfile
- backend_services/matching_service/rmq_server/rmq_server.py
- backend_services/users_service/api/test/get_user_test.py
- docker-compose.yaml
- start_containers.sh
- tests/get_all_questions_test.py
- tests/get_all_sessions_test.py
- tests/get_all_users_test.py
- tests/matching_test.py
- tests/test_codes.py
- Use aio-pika to make rabbitMQ asynchronous
- Change relevant dockerfiles to install
Squashed, rebased and cleaned (removed prints/commented code) version of #175
> Implement matching service

- frontend/src/components/MatchingScreen.tsx
> Fix React warning

- frontend/src/components/EditProfile.tsx
> Add error message for edit profile

- frontend/src/pages/Login.tsx
- frontend/src/pages/Questions.tsx
- frontend/src/pages/Users.tsx
> Prevent premature navigation b4 fetching session

- frontend/src/pages/Questions.tsx
> Allow maintainers to match with others

- backend_services/api_gateway/app/main.py
- backend_services/collaboration_service/api/app/main.py
- frontend/src/pages/Room.tsx
> Implement basic echo in backend for collab websocket

- frontend/src/pages/Room.tsx
Question title, complexity, and description are just placeholders for now.
Will add a confirmation pop up for exit room soon
> Edit UI for collaboration room

- frontend/src/index.css
- frontend/src/pages/Room.tsx
- frontend/src/styles/Room.css
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/93078202/828fc1f1-555b-4c6e-80b6-68d5b3d6ccd8
> Add hidden chatbox component

- frontend/src/components/ChatBox/ChatBox.tsx
- frontend/src/components/ChatBox/ChatMessage.tsx
- frontend/src/components/ChatBox/ChatTab.tsx
- frontend/src/index.css
- frontend/src/pages/Room.tsx
- frontend/src/pages/Signup.tsx
- frontend/src/styles/Room.css
- Will need to change how ChatMessage component is rendered in ChatBox depending on how messages are stored
> Add chatbox component

- .env
- backend.conf
- docker-compose.yaml
The `.env` file is downloadable at:  
https://drive.google.com/drive/u/0/folders/1pGFM7cmDMX6FqOTtUB8VTww2zcnzlsNZ
pls don't accidentally commit it :^)
> Remove `.env` file; move non-secret vars to `backend.conf`

- .gitignore
> Gitignore '.env' file

- frontend/src/styles/QuestionForm.css
- frontend/src/styles/Room.css
@afiqzu Rmb to also format CSS files
> Format frontend code using prettier

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/CollaborationRoom/CodeEditor.tsx
- frontend/src/components/CollaborationRoom/LanguageSelect.tsx
- frontend/src/index.css
- frontend/src/styles/Room.css
--Language dropdown doesn't do anything yet--
> Code editor UI

- frontend/src/components/QuestionTable/DropdownSelect.tsx
- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/styles/QuestionTable.css
- frontend/src/styles/Room.css
Users can now sort questions in question table by ID, Title, Category, and Complexity.
Users can also filter questions based on Complexity. (Will add filtering for other attributes soon)
> Implement sorting and complexity filtering feature

- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/styles/QuestionTable.css
- frontend/src/styles/Room.css
> Implement filtering by category and searching by title

- backend_services/questions_service/database/init.sql
- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
- frontend/src/styles/QuestionTable.css
- Small UI changes to question description display
> Populate Question Table

- format.sh
- pyproject.toml
- requirements.dev.txt
- Added formatter dependencies in `requirements.dev.txt`
- Configured the Python formatters in `pyproject.toml` for:
- autoflake
- black
- isort
- Added `format.sh` script to run formatter on file(s):
```bash
bash format.sh ./path/to/file/or/dir
```
> Setup Python auto-formatters

- backend_services/database_model.py
- backend_services/questions_service/api/app/controllers/questions_controller.py
- backend_services/questions_service/api/app/database_model.py
- backend_services/shared_definitions/shared_definitions/auth/fastapi_dependencies.py
- backend_services/users_service/api/app/controllers/sessions_controller.py
- backend_services/users_service/api/app/controllers/users_controller.py
- backend_services/users_service/api/app/database_model.py
- backend_services/users_service/api/app/utils/users_util.py
> Replace status codes for 'HTTPException' with FastAPI's status const.

- backend_services/users_service/api/app/controllers/users_controller.py
- backend_services/users_service/api/app/main.py
> Remove `DELETE /users_all` API

- backend_services/shared_definitions/shared_definitions/api_models/users.py
> Fix `PUT /users_role/{user_id}` allowing any role

- backend_services/users_service/api/app/controllers/users_controller.py
> Fix last-maintainer check for 'PUT /users_role/{user_id}'

- backend_services/users_service/api/app/controllers/sessions_controller.py
- backend_services/users_service/api/app/main.py
- backend_services/users_service/api/app/utils/sessions_util.py
> Add check for revoked refresh tokens in 'GET /refresh'

- backend_services/questions_service/api/app/controllers/questions_controller.py
- backend_services/questions_service/api/app/main.py
> Fix 'POST /questions' returning status 500 on 'question_id' conflict

- backend_services/questions_service/database/init.sql
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/QuestionTable/DropdownTabs.tsx
- frontend/src/components/QuestionTable/QuestionForm.tsx
- frontend/src/components/QuestionTable/QuestionReadOnlyRow.tsx
- frontend/src/components/QuestionTable/QuestionTable.tsx
- frontend/src/styles/QuestionForm.css
- frontend/src/styles/QuestionTable.css
https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g23/assets/93078202/c7ef3e17-3818-41f0-8482-4b6d047477a6
> Implement markdown for question description

- backend_services/users_service/api/app/controllers/users_controller.py
> Fix incorrect perm check on users APIs

- backend_services/questions_service/api/app/main.py
- backend_services/shared_definitions/pyproject.toml
- backend_services/shared_definitions/shared_definitions/api_models/error.py
- backend_services/shared_definitions/shared_definitions/api_models/questions.py
- backend_services/shared_definitions/shared_definitions/api_models/users.py
- backend_services/users_service/api/app/main.py
> Bug fixes for API validations

- frontend/src/components/ChatBox/ChatBox.tsx
> Fix videochat bug

- backend_services/communication_service/app/main.py
- backend_services/matching_service/app/data_classes.py
- backend_services/matching_service/app/main.py
- backend_services/questions_service/database/init.sql
- backend_services/requirements.txt
- frontend/package.json
- frontend/src/api/matching.ts
- frontend/src/components/ChatBox/ChatBox.tsx
- frontend/src/components/CollaborationRoom/QuestionDescription.tsx
- frontend/src/components/CollaborationRoom/QuestionList.tsx
- frontend/src/components/Matching/MatchSuccess.tsx
- frontend/src/pages/Room.tsx
- frontend/src/stores/questionStore.ts
Allow users to change question of choice when in room.
Will automatically change the question displayed for other user as well.
> Display question when joining room

- check_format.sh
To check if Python file(s) is/are properly formatted:
```bash
bash check_format.sh PATH/TO/FILE/OR/DIR
```
> Create script to check Python format

- nginx.conf
- Turn off logs for API-gateway routes to frontend
- Remove the log user-agents from logs
> Significantly reduce NGINX API-gateway logs

- backend_services/matching_service/app/data_classes.py
- backend_services/matching_service/app/main.py
> Add logging for queue

- backend_services/API_Dockerfile
To reduce memory/CPU-usage of the docker containers during development
> Reduce microservice workers from 4 -> 1

- frontend/src/stores/questionStore.ts
- frontend/src/styles/EditProfile.css
- frontend/src/styles/QuestionForm.css
- frontend/src/styles/Room.css
@Yaladah Set ur VSCode to autoformat (via Prettier extension) for the frontend code.
Instructions here: #211
> Format frontend code with Prettier

- backend_services/code_execution_service/app/env_vars.py
- backend_services/code_execution_service/app/main.py
- backend_services/code_execution_service/judge0/docker-compose.yml
- backend_services/code_execution_service/judge0/judge0.conf
- docker-compose.yaml
- frontend/src/api/codeExecution.ts
- nginx.conf
Haven't integrate with frontend yet.
> Create code-execution service

- frontend/src/components/CollaborationRoom/CodeEditor.tsx
Reverts CS3219-AY2324S1/ay2324s1-course-assessment-g23#331
> Revert "Disable reset code"

- backend_services/communication_service/app/main.py
- backend_services/matching_service/app/main.py
> Protect matching/comms services with FastAPI dependency
